server:
  port: 8092
spring:
  mail:
    host: smtp.exmail.qq.com
    port: 25
    username: dev_guo@patazon.net
    password: Er309uFs
    protocol: smtp
    default-encoding: utf-8
  datasource:
  #数据源基本配置
#    username: root
#    password: gqa123
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://47.107.65.114/db_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    ds1: #数据源1
      driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
      url: jdbc:mysql://47.107.65.114/db_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC #数据源地址
      username: root # 用户名
      password: gqa123 # 密码
    ds2: #数据源1
      driver-class-name: com.mysql.jdbc.Driver # mysql的驱动你可以配置别的关系型数据库
      url: jdbc:mysql://47.107.65.114/db_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC #数据源地址
      username: root # 用户名
      password: gqa123 # 密码
# Redis服务器连接密码（默认为空）
  redis:
    host: 192.168.5.250
    port: 6379
    database: 2
    password: datateam_redis
  #thymeleaf缓存关闭
  thymeleaf:
    cache: false
mybatis-plus:
  type-aliases-package: com.blog.entiy
  #加载mybatis映射文件
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      blog:
        dao: debug

